version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - NODE_ENV=development
    volumes:
      - n8n_data:/home/node/.n8n

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - N8N_BASE_URL=http://n8n:5678/api
      - N8N_API_KEY=${N8N_API_KEY}
      - LOG_LEVEL=info
    depends_on:
      - n8n

volumes:
  n8n_data: 